import type { ElementInfo } from "../types/ElementInfo";

import type {
    LocatorCandidate,
} from "../types/LocatorCandidate";

export function generateLocators(
    element: ElementInfo,
): LocatorCandidate[] {
    const candidates: LocatorCandidate[] = [];

    const iosClassName =
        element.className ??
        (
            element.tagName.startsWith(
                "XCUIElementType",
            )
                ? element.tagName
                : undefined
        );

    const isIOS =
        iosClassName !== undefined;

    /*
     * ========================================
     * Android
     * ========================================
     */

    if (!isIOS) {
        if (element.contentDescription) {
            candidates.push({
                strategy:
                    "accessibilityId",

                value:
                    element.contentDescription,

                score: 100,

                recommended: true,

                reason:
                    "Accessibility ID is readable and usually stable.",
            });
        }

        if (element.resourceId) {
            candidates.push({
                strategy: "id",

                value:
                    element.resourceId,

                score:
                    element.contentDescription
                        ? 95
                        : 100,

                recommended:
                    !element.contentDescription,

                reason:
                    "Resource ID is usually a stable locator.",
            });
        }

        if (element.className) {
            candidates.push({
                strategy: "className",

                value:
                    element.className,

                score: 50,

                recommended: false,

                reason:
                    "Class name may match multiple elements.",
            });
        }

        if (element.text) {
            candidates.push({
                strategy: "xpath",

                value:
                    `//*[@text=${quoteXPath(
                        element.text,
                    )}]`,

                score: 60,

                recommended:
                    candidates.length === 0,

                reason:
                    "Text-based XPath can be useful but may change with UI content.",
            });
        }

        return sortCandidates(
            candidates,
        );
    }

    /*
     * ========================================
     * iOS / XCUITest
     * ========================================
     */

    if (iosClassName) {
        const interactive =
            isInteractiveIOS(
                iosClassName,
            );

        /*
         * Class Name
         *
         * Example:
         * XCUIElementTypeButton
         */
        candidates.push({
            strategy: "className",

            value: iosClassName,

            score: interactive
                ? 70
                : 50,

            recommended: false,

            reason:
                "Class Name is a valid XCUITest selector but may match multiple elements.",
        });

        /*
         * iOS Predicate
         *
         * Prefer name because this
         * matches the selector commonly
         * generated by Appium Inspector.
         *
         * Example:
         * name == "Login"
         */
        if (element.name) {
            candidates.push({
                strategy:
                    "iosPredicate",

                value:
                    `name == ${quotePredicate(
                        element.name,
                    )}`,

                score: 100,

                recommended: true,

                reason:
                    "The element has a name attribute that provides a concise and specific iOS Predicate.",
            });
        } else if (element.label) {
            candidates.push({
                strategy:
                    "iosPredicate",

                value:
                    `label == ${quotePredicate(
                        element.label,
                    )}`,

                score: 90,

                recommended: true,

                reason:
                    "The element exposes a label that can be used as an iOS Predicate.",
            });
        } else {
            candidates.push({
                strategy:
                    "iosPredicate",

                value:
                    `type == ${quotePredicate(
                        iosClassName,
                    )}`,

                score: 70,

                recommended: false,

                reason:
                    "No identifying name or label is available, so the element type is used.",
            });
        }

        /*
  * iOS Class Chain
  *
  * Prefer name when available.
  *
  * The selector uses the element type
  * together with the element name.
  */
        if (element.name) {
            candidates.push({
                strategy:
                    "iosClassChain",

                value:
                    `**/${iosClassName}[` +
                    `name == ${quotePredicate(
                        element.name,
                    )}` +
                    `]`,

                score: 90,

                recommended: false,

                reason:
                    "iOS Class Chain combines the element type with its name for a more specific selector.",
            });
        } else {
            candidates.push({
                strategy:
                    "iosClassChain",

                value:
                    `**/${iosClassName}`,

                score: 75,

                recommended: false,

                reason:
                    "iOS Class Chain uses the element type because no identifying name is available.",
            });
        }

        /*
         * XPath
         *
         * Prefer name because this matches
         * the XPath generated by Appium Inspector.
         *
         * Example:
         * //XCUIElementTypeButton[@name="Login"]
         */
        candidates.push({
            strategy: "xpath",

            value:
                buildIOSXPath(
                    element,
                    iosClassName,
                ),

            score:
                getIOSXPathScore(
                    element,
                ),

            recommended: false,

            reason:
                "XPath uses the element type together with the most specific available iOS attribute.",
        });
    }

    /*
     * ========================================
     * iOS Accessibility ID
     * ========================================
     *
     * IMPORTANT:
     *
     * Do not automatically treat `name`
     * as Accessibility ID.
     *
     * The previous implementation did:
     *
     * element.name ||
     * element.contentDescription
     *
     * This caused selectors such as:
     *
     * Accessibility ID = Login
     *
     * even when the element was not actually
     * accessible.
     */

    const accessibilityName =
        element.accessible
            ? (
                element.name ||
                element.contentDescription
            )
            : undefined;

    if (accessibilityName) {
        candidates.push({
            strategy:
                "accessibilityId",

            value:
                accessibilityName,

            score: 85,

            recommended: false,

            reason:
                "Accessibility ID is generated only when the element is marked as accessible.",
        });
    }

    return sortCandidates(
        candidates,
    );
}

/*
 * ========================================
 * iOS Helpers
 * ========================================
 */

function isInteractiveIOS(
    className: string | undefined,
): boolean {
    if (!className) {
        return false;
    }

    return [
        "XCUIElementTypeButton",
        "XCUIElementTypeTextField",
        "XCUIElementTypeSecureTextField",
        "XCUIElementTypeSwitch",
        "XCUIElementTypeSlider",
        "XCUIElementTypePicker",
        "XCUIElementTypeDatePicker",
        "XCUIElementTypeSearchField",
        "XCUIElementTypeTextView",
    ].includes(className);
}

function buildIOSXPath(
    element: ElementInfo,
    iosClassName: string,
): string {
    /*
     * Appium Inspector commonly produces:
     *
     * //XCUIElementTypeButton[@name="Login"]
     */

    if (element.name) {
        return `//${iosClassName}[@name=${quoteXPath(
            element.name,
        )}]`;
    }

    if (element.label) {
        return `//${iosClassName}[@label=${quoteXPath(
            element.label,
        )}]`;
    }

    if (element.value) {
        return `//${iosClassName}[@value=${quoteXPath(
            element.value,
        )}]`;
    }

    return `//${iosClassName}`;
}

function getIOSXPathScore(
    element: ElementInfo,
): number {
    if (element.name) {
        return 95;
    }

    if (element.label) {
        return 90;
    }

    if (element.value) {
        return 85;
    }

    return 60;
}

function quotePredicate(
    value: string,
): string {
    return `"${value
        .replace(
            /\\/g,
            "\\\\",
        )
        .replace(
            /"/g,
            '\\"',
        )}"`;
}

function quoteXPath(
    value: string,
): string {
    if (!value.includes('"')) {
        return `"${value}"`;
    }

    if (!value.includes("'")) {
        return `'${value}'`;
    }

    const parts =
        value.split('"');

    return `concat(${parts
        .map(
            (part, index) =>
                index <
                    parts.length - 1
                    ? `"${part}", '"', `
                    : `"${part}"`,
        )
        .join("")})`;
}

function sortCandidates(
    candidates: LocatorCandidate[],
): LocatorCandidate[] {
    return candidates.sort(
        (a, b) => b.score - a.score,
    );
}